language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev
    - bash <(curl -s https://codecov.io/bash) -t token
    - export CODECOV_TOKEN="3b92601d-76a7-4ae7-aef6-cb9215455945"
    - bash <(curl -s https://codecov.io/bash)

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
